"""Adjusting Game model

Revision ID: fc7022e52dc0
Revises: 
Create Date: 2024-12-09 03:18:17.469503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc7022e52dc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solution', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('fallback_used', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('fallback_used')
        batch_op.drop_column('solution')

    # ### end Alembic commands ###
