version: "3.8"

services:
  db:
    image: postgres:14
    container_name: mastermind_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: mastermind_app
    environment:
      FLASK_APP: app
      FLASK_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
volumes:
  db_data:
